//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CactpotSolver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CactpotSolver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (0,1510.48)	(1,1453.2)	(2,1510.48)	(3,1453.2)	(4,1510.14)
        ///(5,1453.2)	(6,1510.48)	(7,1453.2)	(8,1510.48)	(11,1619.07)
        ///(12,1677.79)	(13,1619.07)	(14,1677.53)	(15,1533.52)	(16,1677.79)
        ///(17,1533.52)	(18,1634.54)	(21,1611.93)	(22,1665.81)	(23,1611.93)
        ///(24,1664.17)	(25,1510.85)	(26,1665.81)	(27,1510.85)	(28,1620.81)
        ///(31,1606.14)	(32,1662.5)	(33,1606.14)	(34,1661.34)	(35,1509.74)
        ///(36,1662.5)	(37,1509.74)	(38,1616.85)	(41,1302.54)	(42,1356.84)
        ///(43,1302.54)	(44,1365)	(45,1342.53)	(46,1356.84)	(47,1342.53)
        ///(48,1331.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cactpotValues {
            get {
                return ResourceManager.GetString("cactpotValues", resourceCulture);
            }
        }
    }
}
